# Generated by Django 3.2 on 2023-04-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='four_seats_tables',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='more_than_four_seats_tables',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='restaurant_address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='restaurant_type',
            field=models.CharField(blank=True, choices=[('asian', 'Asian'), ('mexican', 'Mexican'), ('italian', 'Italian'), ('french', 'French'), ('greek', 'Greek'), ('american', 'American'), ('indian', 'Indian'), ('turkish', 'Turkish'), ('spanish', 'Spanish'), ('polish', 'Polish')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_seats_tables',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
