# Generated by Django 3.2 on 2023-04-12 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('restaurant_type', models.CharField(choices=[('asian', 'Asian'), ('mexican', 'Mexican'), ('italian', 'Italian'), ('french', 'French'), ('greek', 'Greek'), ('american', 'American'), ('indian', 'Indian'), ('turkish', 'Turkish'), ('spanish', 'Spanish'), ('polish', 'Polish')], max_length=50)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('reserved_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='reservation.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_tables',
            field=models.ManyToManyField(to='reservation.Table'),
        ),
    ]
